# Generated by Django 6.1.1 on 2026-09-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('application_type', models.CharField(choices=[('NEW', 'New Registration'), ('UPDATE', 'Update Information'), ('TRANSFER', 'Transfer'), ('REACTIVATION', 'Reactivation'), ('REINSTATEMENT', 'Reinstatement')], default='NEW', max_length=20)),
                ('pwd_status', models.CharField(choices=[('NO', 'Not PWD'), ('VISUAL', 'Visual Disability'), ('HEARING', 'Hearing Disability'), ('PHYSICAL', 'Physical Disability'), ('INTELLECTUAL', 'Intellectual Disability'), ('PSYCHOSOCIAL', 'Psychosocial Disability'), ('MULTIPLE', 'Multiple Disabilities'), ('OTHER', 'Other')], default='NO', max_length=20)),
                ('citizenship_status', models.CharField(choices=[('BY_BIRTH', 'By Birth'), ('NATURALIZED', 'Naturalized')], default='BY_BIRTH', max_length=20)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved'), ('PENDING', 'Pending'), ('REVIEW', 'Review')], default='PENDING', max_length=20)),
                ('father', models.CharField(max_length=255)),
                ('mother', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_senior', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
