# Generated by Django 6.1.1 on 2026-09-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='municipality',
            field=models.CharField(default='Pio Duran', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='province',
            field=models.CharField(default='Albay', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='brgy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Applicants.barangay'),
        ),
    ]
