# Generated by Django 5.2.17 on 2026-09-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0003_alter_applicant_id_alter_barangay_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_municipality', models.CharField(default='Pio Duran', max_length=255)),
                ('current_province', models.CharField(default='Albay', max_length=255)),
                ('new_municipality', models.CharField(default='Pio Duran', max_length=255)),
                ('new_province', models.CharField(default='Albay', max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='Applicants.applicant')),
                ('current_brgy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_transfer_requests', to='Applicants.barangay')),
                ('new_brgy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_transfer_requests', to='Applicants.barangay')),
            ],
        ),
    ]
