# Generated by Django 5.2.17 on 2026-09-13 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0005_applicantreactivationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantBiometric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_finger', models.FileField(blank=True, null=True, upload_to='biometrics/left/')),
                ('left_finger_template', models.TextField(blank=True, null=True)),
                ('right_finger', models.FileField(blank=True, null=True, upload_to='biometrics/right/')),
                ('right_finger_template', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('biometrics_completed', models.BooleanField(default=False)),
                ('signature_completed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to='Applicants.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantReinstatementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinstatement_requests', to='Applicants.applicant')),
            ],
        ),
    ]
