# Generated by Django 5.2.17 on 2026-09-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0006_applicantbiometric_applicantreinstatementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('BIOMETRICS_PENDING', 'Biometrics Pending'), ('VERIFIED', 'Verified')], default='UNVERIFIED', max_length=30),
        ),
        migrations.CreateModel(
            name='ApplicantNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPROVED', 'Application Approved'), ('BIOMETRICS', 'Biometrics Required'), ('VERIFIED', 'Registration Verified'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Applicants.applicant')),
            ],
        ),
    ]
