# Generated by Django 5.2.17 on 2026-09-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0007_applicant_verification_status_applicantnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='office_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='office_visit_slot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
