# Generated by Django 5.2.17 on 2026-09-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0008_applicant_office_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='civil_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
