# Generated by Django 5.2.17 on 2026-09-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0009_applicant_civil_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantbiometric',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='applicantbiometric',
            name='signature_completed',
        ),
    ]
