# Generated by Django 5.2.17 on 2026-10-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0010_remove_applicantbiometric_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantbiometric',
            name='applicant_signature',
            field=models.FileField(blank=True, null=True, upload_to='biometrics/signatures/'),
        ),
        migrations.AddField(
            model_name='applicantbiometric',
            name='officer_signature',
            field=models.FileField(blank=True, null=True, upload_to='biometrics/signatures/'),
        ),
        migrations.AddField(
            model_name='applicantbiometric',
            name='witness_signature',
            field=models.FileField(blank=True, null=True, upload_to='biometrics/signatures/'),
        ),
    ]
