# Generated by Django 5.2.17 on 2026-10-07 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0011_applicantbiometric_applicant_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantbiometric',
            name='officer_signature',
        ),
        migrations.RemoveField(
            model_name='applicantbiometric',
            name='witness_signature',
        ),
        migrations.CreateModel(
            name='SignatureSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_sessions', to='Applicants.applicant')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
